services:
  command.env.init:
    class: AdnanMula\Chronogg\Notifier\Entrypoint\Command\InitEnvironmentCommand
    arguments:
      - '@repository.dbal.migration.v001'
    tags:
      - { name: console.command, command: 'chronogg:env:init' }

  command.chrono.notify:
    class: AdnanMula\Chronogg\Notifier\Entrypoint\Command\NotifyCurrentDealCommand
    arguments:
      - '@client.deal.chrono'
      - '@client.communication.telegram'
      - '@AdnanMula\Chronogg\Notifier\Domain\Model\User\UserRepository'
    tags:
      - { name: console.command, command: 'chronogg:deal:notify' }

  command.telegram.update:
    class: AdnanMula\Chronogg\Notifier\Entrypoint\Command\TelegramGetUpdatesCommand
    arguments:
      - '%env(TELEGRAM_TOKEN)%'
      - '@client.communication.telegram'
      - '@messenger.bus.command'
    tags:
      - { name: console.command, command: 'chronogg:telegram:update' }