services:
  repository.dbal.connection:
    class: Doctrine\DBAL\Connection
    factory: 'Doctrine\DBAL\DriverManager::getConnection'
    arguments:
      - url: '%db_url%'
        driver: 'pdo_pgsql'

  Doctrine\DBAL\Connection:
    alias: repository.dbal.connection

  repository.dbal.migration:
    class: AdnanMula\Chronogg\Notifier\Infrastructure\Persistence\Repository\DbalMigration
    arguments:
      - '@repository.dbal.connection'

  repository.dbal.repository:
    class: AdnanMula\Chronogg\Notifier\Infrastructure\Persistence\Repository\DbalRepository
    arguments:
      - '@repository.dbal.connection'

  repository.dbal.migration.v001:
    class: AdnanMula\Chronogg\Migrations\Postgres\V001
    parent: 'repository.dbal.migration'