services:
  AdnanMula\Chronogg\Notifier\Domain\Model\User\UserRepository:
    class: AdnanMula\Chronogg\Notifier\Infrastructure\Persistence\Repository\User\UserDbalRepository
    parent: 'repository.dbal.base'