parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    AdnanMula\Chronogg\Notifier\Domain\Service\:
        autowire: true
        autoconfigure: true
        resource: '../src/Domain/Service'

#    AdnanMula\Chronogg\Notifier\Infrastructure\:
#        autowire: true
#        autoconfigure: true
#        resource: '../src/Infrastructure'

    client.communication.telegram:
        class: AdnanMula\Chronogg\Notifier\Infrastructure\Communication\TelegramClient
        arguments:
            - '%env(TELEGRAM_TOKEN)%'
            - '%env(TELEGRAM_GROUP_CHAT_ID)%'
            - '%env(TELEGRAM_ADMIN_CHAT_ID)%'

    client.deal.chrono:
        class: AdnanMula\Chronogg\Notifier\Infrastructure\Chrono\ChronoClient

    command.chrono.notify:
        class: AdnanMula\Chronogg\Notifier\Entrypoint\Command\NotifyCurrentDealCommand
        arguments:
            - '@client.deal.chrono'
            - '@client.communication.telegram'
        tags:
            - { name: console.command, command: 'chronogg:deal:notify' }