parameters:
    db_url: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    AdnanMula\Chronogg\Notifier\Domain\Service\:
        autowire: true
        autoconfigure: true
        resource: '../src/Domain/Service'

    AdnanMula\Chronogg\Notifier\Infrastructure\Service\:
        autowire: true
        autoconfigure: true
        resource: '../src/Infrastructure/Service'

    AdnanMula\Chronogg\Notifier\Infrastructure\Persistence\Repository\:
        autowire: true
        autoconfigure: true
        resource: '../src/Infrastructure/Persistence/Repository'

imports:
    - { resource: context/system/buses.yaml }
    - { resource: context/system/repositories.yaml }
    - { resource: context/system/commands.yaml }
    - { resource: context/user/repositories.yaml }
    - { resource: context/deal/services.yaml }